apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: angular-jumpstart
build:
  artifacts:
  - image: nginx-angular-jumpstart
    context: .
    sync: 
      manual:
      - src: "./dist"
        dest: "/usr/share/nginx/html"
    docker:
      dockerfile: .docker/nginx.dev.dockerfile
  - image: node-service-jumpstart
    context: .
    docker:
      dockerfile: .docker/node.dockerfile
deploy:
  kubectl:
    manifests:
    - .k8s/*.yml
